FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD Crackpokemon94!  
ENV MYSQL_DATABASE RampUp 
ENV MYSQL_USER IGonzalez  
ENV MYSQL_PASSWORD Crackpokemon94!

ADD RampUpScript.sql /docker-entrypoint-initdb.d

EXPOSE 3306

